# CMake generated Testfile for 
# Source directory: /home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite
# Build directory: /home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/resources
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(formula_test "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/resources/tests/formula/formula_test")
set_tests_properties(formula_test PROPERTIES  _BACKTRACE_TRIPLES "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;153;add_test;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;0;;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;51;include;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;0;")
add_test(transformation_test "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/resources/tests/formula/transformation_test")
set_tests_properties(transformation_test PROPERTIES  _BACKTRACE_TRIPLES "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;154;add_test;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;0;;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;51;include;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;0;")
add_test(parser_test "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/resources/tests/parser/parser_test")
set_tests_properties(parser_test PROPERTIES  _BACKTRACE_TRIPLES "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;155;add_test;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;0;;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;51;include;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;0;")
add_test(nnf_test "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/resources/tests/transformation/nnf_test")
set_tests_properties(nnf_test PROPERTIES  _BACKTRACE_TRIPLES "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;158;add_test;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;0;;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;51;include;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;0;")
add_test(xnf_test "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/resources/tests/transformation/xnf_test")
set_tests_properties(xnf_test PROPERTIES  _BACKTRACE_TRIPLES "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;159;add_test;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;0;;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;51;include;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;0;")
add_test(dfa_test "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/resources/tests/automata/dfa_test")
set_tests_properties(dfa_test PROPERTIES  _BACKTRACE_TRIPLES "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;162;add_test;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;0;;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;51;include;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;0;")
add_test(tarjan_test "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/resources/tests/automata/tarjan_test")
set_tests_properties(tarjan_test PROPERTIES  _BACKTRACE_TRIPLES "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;163;add_test;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;0;;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;51;include;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;0;")
add_test(progression_test "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/resources/tests/automata/progression_test")
set_tests_properties(progression_test PROPERTIES  _BACKTRACE_TRIPLES "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;164;add_test;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;0;;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;51;include;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;0;")
add_test(synthesis_test "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/resources/tests/synthesis/synthesis_test")
set_tests_properties(synthesis_test PROPERTIES  _BACKTRACE_TRIPLES "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;167;add_test;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;0;;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;51;include;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;0;")
add_test(on_the_fly_test "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/resources/tests/synthesis/on_the_fly_test")
set_tests_properties(on_the_fly_test PROPERTIES  _BACKTRACE_TRIPLES "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;168;add_test;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;0;;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;51;include;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;0;")
add_test(prop_atoms_test "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/resources/tests/integration/prop_atoms_test")
set_tests_properties(prop_atoms_test PROPERTIES  _BACKTRACE_TRIPLES "/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;171;add_test;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/cmake/Tests.cmake;0;;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;51;include;/home/lic/files/rewrite_ltlf_codes/CosyZeroRewrite/CMakeLists.txt;0;")
